name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - testing
      - production
  pull_request:
    branches:
      - "*"

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npm run prisma:generate

      - name: Type checking
        run: npm run type-check

      - name: Lint check
        run: npm run lint:check

      - name: Build application
        run: npm run build
